name: ZenPlugin
main: bzh.strawberry.zenplugin.ZenPlugin
version: 0.1.0
author: Uicias
api-version: 1.16
description: Plugin for Zennit_
commands:
  hat:
    description: allow a player to place an item on his head
  caca:
    description: Une demande spéciale d'Eclixal