name: HomesPlugin
main: com.uicias.homeplugin.HomePlugin
version: 0.0.1
author: Uicias
api-version: 1.15
description: Plugin to manage the homes
commands:
  sethome:
    description: set a home for the user
  home:
    description: teleport a player to a home
  delhome:
    description: allow a player to delete a home
  warp:
    description: allow a player to teleport himself to a warp
  setwarp:
    description: allow an operator to create a warp
  delwarp:
    description: allow an operator to delete a warp
  hat:
    description: allow a player to place an item on his head